# Generated by Django 6.0.7 on 2026-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AddField(
            model_name='product',
            name='package_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Výška balíku (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Délka balíku (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Váha balíku (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Šířka balíku (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Výška produktu (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Délka produktu (mm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Váha produktu (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Šířka produktu (mm)'),
        ),
    ]
