# Generated by Django 6.0.7 on 2026-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_remove_product_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Package height (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Package length (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Package weight (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='package_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Package width (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Product height (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Product length (mm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Product weight (g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Product width (mm)'),
        ),
    ]
