# Generated by Django 6.0.7 on 2026-08-08 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='Souhlas s podmínkami individuální objednávky')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Poptávka na míru',
                'verbose_name_plural': 'Poptávky na míru',
            },
        ),
    ]
