# Generated by Django 6.0.7 on 2026-08-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_quoterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='name',
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Jméno'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Příjmení'),
        ),
    ]
