# Generated by Django 6.0.7 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.CharField(blank=True, max_length=100)),
                ('contact_last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('ico', models.CharField(max_length=20)),
                ('dic', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_billing', to='catalog.profile')),
            ],
        ),
    ]
