# Generated by Django 6.0.7 on 2026-09-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_different',
            field=models.BooleanField(default=False),
        ),
    ]
