# Generated by Django 6.0.7 on 2026-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_order_billing_different'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billing_different',
            field=models.BooleanField(default=False),
        ),
    ]
